# Generated by Django 5.1.1 on 2024-09-24 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    categories = [
        'Electronics',
        'Home Appliances',
        'Furniture',
        'Clothing',
        'Food & Beverages',
        'Health & Beauty',
        'Toys & Games',
        'Sports & Outdoors',
        'Automotive',
        'Office Supplies',
    ]
    for category in categories:
        Category.objects.get_or_create(name=category)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_quantity_in_stock', models.IntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.RunPython(create_initial_categories),  # Add this line

    ]
